#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   

import = ["/home/daniel/.config/alacritty/catppuccin/catppuccin-mocha.toml", "/home/daniel/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true
blink_interval = 550
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "Full"
# position = { x = 0, y = 0 }
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12
